#!/usr/bin/python3

import amulet

def deploy_openvim():
    d = amulet.Deployment()
    d.add("mysql", series="trusty")
    d.add("openvim-controller", series="xenial")
    d.add("openvim-compute", charm="local:xenial/openvim-compute", series="xenial")
    d.relate("openvim-controller:db", "mysql:db")
    d.relate("openvim-controller:compute", "openvim-compute:compute")
    d.setup()
    d.sentry.wait()

deploy_openvim() # yay
